[credentials]
gemini_api_key = YOUR_GEMINI_API_KEY_HERE
ollama_api_key = 390b76fb236f48ebbf19b60c4781ba6e.DoRm3P8CaA2swUIPXUxH12uu

[models]
# Gemini models
gemini_models = gemini-flash-latest, gemini-3-flash-preview, gemini-2.5-flash, gemini-2.5-flash-lite, gemini-robotics-er-1.5-preview, gemma-4-26b-a4b-it, gemma-4-31b-it
# Ollama model
ollama_model = gpt-oss:120b-cloud

[settings]
# Choose: gemini or ollama
ai_provider = ollama
language = arabic
# Choose: translate or summary
type = summary
