[credentials]
ollama_api_key = 390b76fb236f48ebbf19b60c4781ba6e.DoRm3P8CaA2swUIPXUxH12uu

[models]
ollama_models = gpt-oss:120b-cloud, gpt-oss:20b, gemma4:31b-cloud

[settings]
language = arabic
# Choose: translate or summary
type = summary
# Number of posts to keep per feed (default: 20)
max_posts = 20
# Merge all feeds into one XML file: yes or no
merge_feeds = yes
